// clients.js — dummy client data
// Field names match the Client mongoose schema: name, phone, email, address, gst,
// totalProjects, totalRevenue, pendingAmount, status, city, state, zipCode, notes

module.exports = [
  {
    name:          "Rahul & Priya Sharma",
    phone:         "9876543210",
    email:         "rahul.sharma@gmail.com",
    address:       "42, Rose Garden Colony",
    city:          "Jaipur",
    state:         "Rajasthan",
    zipCode:       "302001",
    gst:           "",
    status:        "Active",
    totalProjects: 2,
    totalRevenue:  350000,
    pendingAmount: 50000,
    notes:         "Referred by Mehra family. Preferred photographer: Arjun.",
  },
  {
    name:          "Ankita & Vikram Mehra",
    phone:         "9812345678",
    email:         "ankita.mehra@outlook.com",
    address:       "17, Shanti Nagar, Sector 12",
    city:          "Gurugram",
    state:         "Haryana",
    zipCode:       "122001",
    gst:           "06AABCU9603R1Z8",
    status:        "Active",
    totalProjects: 1,
    totalRevenue:  180000,
    pendingAmount: 0,
    notes:         "Very detail-oriented. Requires previews within 48 hours.",
  },
  {
    name:          "Sneha Patel",
    phone:         "9898989898",
    email:         "sneha.patel@yahoo.com",
    address:       "5, Ashoka Society, Navrangpura",
    city:          "Ahmedabad",
    state:         "Gujarat",
    zipCode:       "380009",
    gst:           "",
    status:        "Potential",
    totalProjects: 0,
    totalRevenue:  0,
    pendingAmount: 0,
    notes:         "Enquired for maternity shoot in August.",
  },
  {
    name:          "Rohan & Kavita Joshi",
    phone:         "9711111111",
    email:         "rohan.joshi@gmail.com",
    address:       "88, Dwarka Sector 10",
    city:          "New Delhi",
    state:         "Delhi",
    zipCode:       "110075",
    gst:           "",
    status:        "Active",
    totalProjects: 3,
    totalRevenue:  520000,
    pendingAmount: 75000,
    notes:         "Long-term client. Books every major family event.",
  },
  {
    name:          "Divya & Arun Kumar",
    phone:         "9500001234",
    email:         "divya.arun@gmail.com",
    address:       "12, RA Puram, 3rd Main Road",
    city:          "Chennai",
    state:         "Tamil Nadu",
    zipCode:       "600028",
    gst:           "",
    status:        "Active",
    totalProjects: 1,
    totalRevenue:  220000,
    pendingAmount: 40000,
    notes:         "South Indian traditional wedding. Requires Tamil-speaking coordinator.",
  },
  {
    name:          "Preeti Kapoor",
    phone:         "9654321098",
    email:         "preeti.kapoor@hotmail.com",
    address:       "204, Vaishali Nagar",
    city:          "Jaipur",
    state:         "Rajasthan",
    zipCode:       "302021",
    gst:           "",
    status:        "Inactive",
    totalProjects: 1,
    totalRevenue:  85000,
    pendingAmount: 0,
    notes:         "One-time birthday shoot. Did not respond to follow-ups.",
  },
  {
    name:          "Tech Horizon Pvt Ltd",
    phone:         "9022334455",
    email:         "events@techhorizon.in",
    address:       "Tower B, BKC, Bandra Kurla Complex",
    city:          "Mumbai",
    state:         "Maharashtra",
    zipCode:       "400051",
    gst:           "27AABCT1332L1Z9",
    status:        "Active",
    totalProjects: 2,
    totalRevenue:  480000,
    pendingAmount: 100000,
    notes:         "Corporate client. Invoices required within 3 days of shoot.",
  },
  {
    name:          "Nisha & Deepak Verma",
    phone:         "9411223344",
    email:         "nisha.verma@rediffmail.com",
    address:       "63, Civil Lines",
    city:          "Lucknow",
    state:         "Uttar Pradesh",
    zipCode:       "226001",
    gst:           "",
    status:        "Potential",
    totalProjects: 0,
    totalRevenue:  0,
    pendingAmount: 0,
    notes:         "Interested in wedding package. Budget around ₹2L.",
  },
];
