// events.js — dummy event data
// Fields match the Event mongoose schema.
// Note: clientName and projectName are used as symbolic links for seeding logic.

module.exports = [
  {
    clientName:        "Rahul & Priya Sharma",
    projectName:       "Sharma-Patel Wedding",
    eventName:         "Mehendi Ceremony",
    eventType:         "Wedding",
    eventDate:         "2025-11-14",
    startTime:         "14:00",
    endTime:           "18:00",
    venue:             "ITC Rajputana Hotel, Jaipur",
    mapsLink:          "https://maps.app.goo.gl/example1",
    status:            "Completed",
    assignedTeam:      "Team A (Arjun, Neha)",
    equipmentRequired: "2x Sony A7IV, DJI Mavic 3",
    notes:             "Focus on candid shots of the bride's family.",
  },
  {
    clientName:        "Rahul & Priya Sharma",
    projectName:       "Sharma-Patel Wedding",
    eventName:         "Sangeet & Cocktail",
    eventType:         "Wedding",
    eventDate:         "2025-11-14",
    startTime:         "20:00",
    endTime:           "02:00",
    venue:             "ITC Rajputana Hotel, Jaipur",
    mapsLink:          "https://maps.app.goo.gl/example1",
    status:            "Completed",
    assignedTeam:      "Team A (Arjun, Neha, Rohit)",
    equipmentRequired: "2x Sony A7IV, Gimbal, Godox AD200",
    notes:             "Requires flash photography. Client requested specific family group shots.",
  },
  {
    clientName:        "Rahul & Priya Sharma",
    projectName:       "Sharma-Patel Wedding",
    eventName:         "Wedding Ceremony",
    eventType:         "Wedding",
    eventDate:         "2025-11-15",
    startTime:         "18:00",
    endTime:           "23:30",
    venue:             "ITC Rajputana Hotel, Jaipur",
    mapsLink:          "https://maps.app.goo.gl/example1",
    status:            "Completed",
    assignedTeam:      "Team A & B (Arjun, Neha, Rohit, Vikram)",
    equipmentRequired: "Drone, 4 Cams, Audio Recorders",
    notes:             "Pheras at sunset. Use drone for aerial view of mandap.",
  },
  {
    clientName:        "Ankita & Vikram Mehra",
    projectName:       "Mehra Reception Night",
    eventName:         "Grand Reception",
    eventType:         "Reception",
    eventDate:         "2025-10-22",
    startTime:         "19:30",
    endTime:           "23:00",
    venue:             "Taj City Centre, Gurugram",
    mapsLink:          "https://maps.app.goo.gl/example2",
    status:            "Completed",
    assignedTeam:      "Team C (Ravi, Sneha)",
    equipmentRequired: "Stage lighting, Telephoto lens",
    notes:             "Focus on stage group pictures. VVIP guests attending.",
  },
  {
    clientName:        "Divya & Arun Kumar",
    projectName:       "Kumar-Shankar Wedding",
    eventName:         "Nalangu & Mehndi",
    eventType:         "Wedding",
    eventDate:         "2026-04-02",
    startTime:         "16:00",
    endTime:           "20:00",
    venue:             "Sri Kapali Temple Hall, Mylapore",
    mapsLink:          "https://maps.app.goo.gl/example3",
    status:            "Scheduled",
    assignedTeam:      "Team B (Vikram, Priya)",
    equipmentRequired: "Standard Kit",
    notes:             "Traditional ceremonies. Wear appropriate attire.",
  },
  {
    clientName:        "Divya & Arun Kumar",
    projectName:       "Kumar-Shankar Wedding",
    eventName:         "Muhurtham",
    eventType:         "Wedding",
    eventDate:         "2026-04-03",
    startTime:         "06:30",
    endTime:           "10:30",
    venue:             "Sri Kapali Temple, Mylapore",
    mapsLink:          "https://maps.app.goo.gl/example3",
    status:            "Scheduled",
    assignedTeam:      "Team B (Vikram, Priya)",
    equipmentRequired: "Standard Kit, Gimbal",
    notes:             "Early morning start. Catch the exact thali tying moment.",
  },
  {
    clientName:        "Tech Horizon Pvt Ltd",
    projectName:       "Tech Horizon Annual Day 2025",
    eventName:         "Annual Awards Night",
    eventType:         "Corporate",
    eventDate:         "2025-12-20",
    startTime:         "17:00",
    endTime:           "22:30",
    venue:             "NSCI Dome, Mumbai",
    mapsLink:          "https://maps.app.goo.gl/example4",
    status:            "Completed",
    assignedTeam:      "Team Corporate (Sanjay, Amit)",
    equipmentRequired: "70-200mm lens, Multiple Flashes",
    notes:             "Keynote speech at 6 PM. Award distributions at 8 PM.",
  }
];
