// projects.js — dummy project data
// NOTE: clientName here should match the client name for readability, but
//       projectId references are resolved dynamically in the seed script.
// Fields match the Project mongoose schema.

// These use symbolic client names; seed.js maps them to actual ObjectIds.
module.exports = [
  {
    projectName: "Sharma-Patel Wedding",
    clientName:  "Rahul & Priya Sharma",
    phone:       "9876543210",
    email:       "rahul.sharma@gmail.com",
    address:     "42, Rose Garden Colony, Jaipur",
    eventType:   "Wedding",
    location:    "ITC Rajputana Hotel, Jaipur",
    startDate:   "2025-11-14",
    endDate:     "2025-11-15",
    totalAmount: 250000,
    advance:     100000,
    balance:     150000,
    status:      "Completed",
    notes:       "Full 2-day wedding coverage. Drone permitted.",
  },
  {
    projectName: "Rahul & Priya — Honeymoon Album",
    clientName:  "Rahul & Priya Sharma",
    phone:       "9876543210",
    email:       "rahul.sharma@gmail.com",
    address:     "",
    eventType:   "Commercial",
    location:    "Udaipur, Rajasthan",
    startDate:   "2025-12-05",
    endDate:     "2025-12-06",
    totalAmount: 100000,
    advance:     50000,
    balance:     50000,
    status:      "Completed",
    notes:       "Pre-wedding style album at City Palace Udaipur.",
  },
  {
    projectName: "Mehra Reception Night",
    clientName:  "Ankita & Vikram Mehra",
    phone:       "9812345678",
    email:       "ankita.mehra@outlook.com",
    address:     "Taj City Centre, Gurugram",
    eventType:   "Reception",
    location:    "Taj City Centre, Gurugram",
    startDate:   "2025-10-22",
    endDate:     "2025-10-22",
    totalAmount: 180000,
    advance:     180000,
    balance:     0,
    status:      "Completed",
    notes:       "Night reception. Extra light equipment needed.",
  },
  {
    projectName: "Joshi 25th Anniversary",
    clientName:  "Rohan & Kavita Joshi",
    phone:       "9711111111",
    email:       "rohan.joshi@gmail.com",
    address:     "88, Dwarka Sector 10, New Delhi",
    eventType:   "Birthday",
    location:    "The Imperial, New Delhi",
    startDate:   "2026-03-18",
    endDate:     "2026-03-18",
    totalAmount: 120000,
    advance:     60000,
    balance:     60000,
    status:      "Completed",
    notes:       "Silver anniversary party. Photo + video + same-day edit.",
  },
  {
    projectName: "Joshi Family Portrait",
    clientName:  "Rohan & Kavita Joshi",
    phone:       "9711111111",
    email:       "rohan.joshi@gmail.com",
    address:     "",
    eventType:   "Commercial",
    location:    "Studio — In-house",
    startDate:   "2026-01-10",
    endDate:     "2026-01-10",
    totalAmount: 35000,
    advance:     35000,
    balance:     0,
    status:      "Completed",
    notes:       "Family of 8. 3-hour studio session.",
  },
  {
    projectName: "Joshi Son Engagement",
    clientName:  "Rohan & Kavita Joshi",
    phone:       "9711111111",
    email:       "rohan.joshi@gmail.com",
    address:     "",
    eventType:   "Engagement",
    location:    "Lodhi Garden, New Delhi",
    startDate:   "2026-08-10",
    endDate:     "2026-08-10",
    totalAmount: 80000,
    advance:     20000,
    balance:     60000,
    status:      "Upcoming",
    notes:       "Outdoor engagement at Lodhi Garden. Golden hour shoot.",
  },
  {
    projectName: "Kumar-Shankar Wedding",
    clientName:  "Divya & Arun Kumar",
    phone:       "9500001234",
    email:       "divya.arun@gmail.com",
    address:     "12, RA Puram, Chennai",
    eventType:   "Wedding",
    location:    "Sri Kapali Temple, Mylapore",
    startDate:   "2026-04-02",
    endDate:     "2026-04-03",
    totalAmount: 220000,
    advance:     100000,
    balance:     120000,
    status:      "Upcoming",
    notes:       "Traditional Tamil Brahmin wedding. Coverage includes nalangu & muhurtham.",
  },
  {
    projectName: "Kapoor Birthday Bash",
    clientName:  "Preeti Kapoor",
    phone:       "9654321098",
    email:       "preeti.kapoor@hotmail.com",
    address:     "204, Vaishali Nagar, Jaipur",
    eventType:   "Birthday",
    location:    "Private Residence, Jaipur",
    startDate:   "2025-07-15",
    endDate:     "2025-07-15",
    totalAmount: 85000,
    advance:     85000,
    balance:     0,
    status:      "Completed",
    notes:       "30th birthday surprise party. 4-hour coverage.",
  },
  {
    projectName: "Tech Horizon Annual Day 2025",
    clientName:  "Tech Horizon Pvt Ltd",
    phone:       "9022334455",
    email:       "events@techhorizon.in",
    address:     "Tower B, BKC, Mumbai",
    eventType:   "Corporate",
    location:    "NSCI Dome, Mumbai",
    startDate:   "2025-12-20",
    endDate:     "2025-12-20",
    totalAmount: 280000,
    advance:     200000,
    balance:     80000,
    status:      "Completed",
    notes:       "Corporate annual day. Keynote + awards + networking. GST invoice required.",
  },
  {
    projectName: "Tech Horizon Product Launch",
    clientName:  "Tech Horizon Pvt Ltd",
    phone:       "9022334455",
    email:       "events@techhorizon.in",
    address:     "",
    eventType:   "Corporate",
    location:    "JW Marriott, Juhu, Mumbai",
    startDate:   "2026-09-05",
    endDate:     "2026-09-05",
    totalAmount: 200000,
    advance:     100000,
    balance:     100000,
    status:      "Upcoming",
    notes:       "Product launch event. Live stream coverage required.",
  },
];
